
packages = [ "pyudunits2", "micropip",
  "lxml",
  "cftime>=1.1.0",
  "isodate>=0.6.1",
  "jinja2>=2.7.3",
  "lxml>=3.2.1",
  "netcdf4>=1.6.4",
  "owslib>=0.8.3",
  "packaging",
  "pendulum>=1.2.4",
  "pygeoif>=0.6",
  "pyproj>=2.2.1",
  "pyudunits2",
  "regex>=2017.07.28",
  "requests>=2.2.1",
  "setuptools>=15.0",
  "shapely>=1.7.1",
  "validators>=0.14.2",
  "panel",
  "./static/wheels/compliance_checker-5.3.1.dev55+gb1b0b0c-py3-none-any.whl", ]



